steps:
  - label: annotate
    # plugins:
    #   - bugcrowd/test-summary#v1.8.0:
    #       inputs:
    #         - label: rspec
    #           artifact_path: artifacts/rspec*
    #           type: junit
    #       formatter:
    #         type: details
    #       context: test-summary
    command: "touch artifacts/report.xml"
    artifact_paths: "artifacts/*.xml"
  - wait
  - label: "Annotate test results"
    command: ":true"

