steps:
  - label: "Run the script"
    command: "./script.sh"
    key: "script-step"
    soft_fail: true
  - label: "Block build only if lint failed"
    depends_on: "script-step"
    command: |
      if [ $(buildkite-agent step get "outcome" --step "script-step") == "soft_failed" ]; then
         cat <<- YAML | buildkite-agent pipeline upload
         steps:
           - label: "Update commit status"
             command: "echo Notifying GitHub"
             notify:
               - github_commit_status:
                   context: "my-custom-status"
      YAML
      fi