steps:
  - label: "Store result"
    command: |
      buildkite-agent meta-data set "deployment-result" "SOURCE METADATA"
    meta_data:
      SOURCE_BUILD_ID: "${BUILDKITE_BUILD_ID}"
  - trigger: pipeline-2
    build:
      env:
        PREVIOUS_BUILD_NUMBER: "${BUILDKITE_BUILD_NUMBER}"
        # SOURCE_BUILD_ID: "${BUILDKITE_BUILD_ID}"