steps:
  - label: "Store result"
    command: |
      result=$(some-command-that-returns-value)
      buildkite-agent meta-data set "deployment-result" "$result"
  
  - trigger: pipeline-2
    build:
      meta_data:
        source_build_id: "${BUILDKITE_BUILD_ID}"